In [1]:
import numpy as np

## Создаем признаки x, y, z

In [2]:
SIZE = 1000
np.random.seed(123)
x = np.random.normal(size=SIZE)
y = np.random.normal(size=SIZE)

In [3]:
z = (x + y) / 2

## Объединяем все эти значения в матрицу F

In [4]:
F = np.vstack([x, y, z])

## Вычисляем матрицу Грама

In [5]:
FF = 1 / SIZE * F @ F.T

In [13]:
FF

array([[ 1.00314102, -0.03032538,  0.48640782],
       [-0.03032538,  0.91785269,  0.44376365],
       [ 0.48640782,  0.44376365,  0.46508574]])

## Вычисляем собственные векторы и собственные числа

In [6]:
L, W = np.linalg.eig(FF)

In [18]:
sorted(L, reverse=True)

[np.float64(1.4018930165258376),
 np.float64(0.9841864212968798),
 np.float64(0.0)]

In [10]:
L.shape

(3,)

In [9]:
W

array([[ 0.40824829,  0.66187026, -0.62869793],
       [ 0.40824829,  0.4836216 ,  0.77423735],
       [-0.81649658,  0.57274593,  0.07276971]])

In [11]:
W.shape

(3, 3)

### Сортируем собственные векторы по убыванию собственных чисел:

In [7]:
WW = sorted(zip(L, W.T), key=lambda lx: lx[0], reverse=True)

In [15]:
WW = np.array([w[1] for w in WW])

In [16]:
WW.shape

(3, 3)

In [17]:
WW

array([[ 0.66187026,  0.4836216 ,  0.57274593],
       [-0.62869793,  0.77423735,  0.07276971],
       [ 0.40824829,  0.40824829, -0.81649658]])